# Generated by Django 4.2.6 on 2023-11-06 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rps_app', '0002_rename_name_info_sname'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
